#!/bin/sh
# Issue #15: an environment variable must win over config/defaults.conf.
. "$(dirname "$0")/lib.sh"
cd "$TOOLKIT" || exit 1

# Directly through a numbered script: the shipped config says DRY_RUN=0.
chmod 644 /etc/shadow
out=$(DRY_RUN=1 sh scripts/05-file-permissions.sh 2>&1)
check "DRY_RUN=1 in the environment makes the script simulate" \
    has_line "$out" "DRY-RUN\] Would secure file permissions"
check_eq "/etc/shadow unchanged under DRY_RUN=1" "644" "$(mode_of /etc/shadow)"

# Values from a script's point of view, via the same loader.
probe() {
    sh -c '. lib/config.sh; load_config "$1"; echo "$DRY_RUN|$SAFETY_MODE|$ADMIN_IP|$SSH_PORT"' _ "$1"
}
check_eq "file values apply when the environment is silent" \
    "0|1||22" "$(probe config/defaults.conf)"
check_eq "environment beats the file" \
    "1|1|203.0.113.9|2200" "$(DRY_RUN=1 ADMIN_IP=203.0.113.9 SSH_PORT=2200 probe config/defaults.conf)"
check_eq "an empty environment value does not blank the file value" \
    "0|1||22" "$(SSH_PORT= probe config/defaults.conf)"

# A config generated by the Ansible template (older format, plain assignments).
cat > /tmp/ansible.conf <<'CONF'
DRY_RUN=0
SAFETY_MODE=1
ADMIN_IP="198.51.100.4"
SSH_PORT=22
ROLLBACK_ENABLED=1
CONF
check_eq "environment beats an Ansible-style config" \
    "1|1|198.51.100.4|22" "$(DRY_RUN=1 probe /tmp/ansible.conf)"

finish
